ESharpMashtiHasan/Controllers/EmployeeManagementController.cs
using FramWork.DTOS;
using Microsoft.AspNetCore.Mvc;
using Shapping.DomainModel.BusinessModel.Employee;
using Shopping.ApplicationServiceContract.Services;

namespace ESharpMashtiHasan.Controllers
{
	public class EmployeeManagementController : Controller
	{
		private readonly IEmployeeApplication IEmpApp;
        public EmployeeManagementController(IEmployeeApplication IEmpApp)
        {
            this.IEmpApp = IEmpApp;
        }

        public IActionResult Index(EmployeeSearchModel sm )
		{
			return View(sm);
		}
		[HttpPost]
		public JsonResult Delete(int id)
		{
			OperationResult op = IEmpApp.Remove(id);
			return Json(op);
		}
		public IActionResult Search(EmployeeSearchModel sm)
		{
			return ViewComponent("EmployeeList", sm);
		}
        public IActionResult AddNew()
        {
            return View();
        }
		[HttpPost]
        public IActionResult AddNew(EmployeeAddEditModel emp)
        {

            return View();
        }
    }
}

ESharpMashtiHasan/ViewComponents/EmployeeListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shapping.DomainModel.BusinessModel.Employee;
using Shapping.DomainModel.BusinessModel.Product;
using Shopping.ApplicationServiceContract.Services;

namespace ESharpMashtiHasan.ViewComponents
{
	[ViewComponent(Name = "EmployeeList")]
	public class EmployeeListViewComponent : ViewComponent
	{
		public readonly IEmployeeApplication RepoEmp;
        public EmployeeListViewComponent(IEmployeeApplication RepoEmp)
        {
            this.RepoEmp = RepoEmp;	
        }

        public IViewComponentResult Invoke(EmployeeSearchModel sm)
		{
			int rc = 0;
			var employees = RepoEmp.Search(sm , out rc);
			Models.EmployeeListAndSearchModel psm = new Models.EmployeeListAndSearchModel
			{
				sm = sm,
				employeeListItems = employees,
			};
			sm.RecordCount = rc;
			if(sm.PageSize == 0)
			{
				sm.PageSize = 5;
			}
			if(sm.RecordCount % sm .PageSize  == 0)
			{
				sm.PageCount = sm.RecordCount / sm .PageSize; 
			}
			else
			{
				sm.PageCount = sm.RecordCount / sm.PageSize + 1;

			}
			return View(psm );
		}
	}
}

ESharpMashtiHasan/Views/EmployeeManagement/AddNew.cshtml
@model ESharpMashtiHasan.ViewModel.Employee.EmployeeAddAndEditViewModel
@{
	Layout = null;
}
<form asp-action="AddNew" asp-controller="EmployeeManagement" method="post">
    <table class="table table-bordered table-hover table-striped">
        <tr>
            <td>
                FirstName
            </td>
            <td>
                <input type="text" asp-for="FirstName" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                LastName
            </td>
            <td>
                <input type="text" asp-for="LastName" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                Age
            </td>
            <td>
                <input type="text" asp-for="Age" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                AddressID
            </td>
            <td>
                <input type="text" asp-for="AddressID" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                Evidence
            </td>
            <td>
                <input type="text" asp-for="Evidence" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                Position
            </td>
            <td>
                <input type="text" asp-for="Position" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>
                MobileNumber
            </td>
            <td>
                <input type="text" asp-for="MobileNumber" class="form-control" />
            </td>
        </tr>
        <tr>
            <td colspan="2" class="text-center">
                <input type="submit" class="btn-success" value="AddNew" name="name" />
                <span class="btn btn-danger" id="btnCancel">Cancel</span>
            </td>
        </tr>
    </table>
</form>

ESharpMashtiHasan/Views/EmployeeManagement/Index.cshtml
@model Shapping.DomainModel.BusinessModel.Employee.EmployeeSearchModel
<form method="get" asp-action="Index" asp-controller="EmployeeManagement" id="frmSearchEmp">
	<table class="table table-hover table-striped table-sm table-bordered">
		<tr>
			<td><label for="FirstName">First Name</label></td>
			<td>
				<input type="text" asp-for="FirstName" class="form-control" placeholder="FirstName" />
			</td>
		</tr>
		<tr>
			<td><label for="LastName">Last Name</label></td>
			<td>
				<input type="text" asp-for="LastName" class="form-control" placeholder="LastName" />
			</td>
		</tr>
		<tr>
			<td><label for="Age">Age</label></td>
			<td>
				<input type="text" asp-for="Age" class="form-control" placeholder="Age" />
			</td>
		</tr>
		<tr>
			<td class="text-center" colspan="2">
				<input type="submit" value="Search" class="btn btn-success" />
				<a asp-action="Index" asp-controller="EmployeeManagement" class="btn btn-primary">Remove Filter</a>
				<span class="btn btn-primary" id="btnAddNewEmployee">Add New</span>
			</td>
		</tr>
	</table>
	<div id="dvContent">
		@await Component.InvokeAsync("EmployeeList", this.Model)
	</div>
	
</form>