ESharpMashtiHasan/Controllers/ProductManagementController.cs
using ESharpMashtiHasan.ViewModel.Products;
using FramWork.DTOS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Shapping.DomainModel.BusinessModel.Category;
using Shapping.DomainModel.BusinessModel.Product;
using Shapping.DomainModel.Models;
using Shopping.ApplicationServiceContract.Services;
using FramWork;
using ESharpMashtiHasan.Utility;

namespace ESharpMashtiHasan.Controllers
{
	public class ProductManagementController : Controller
	{
		#region DataLoader

		private void InflateCategoryDrp()
		{
			var cats = ICategoryApp.GetDrp();
			cats.Insert(0, new FastCatList { CategoryID = -1, CategoryName = "...Please Select..." });
			SelectList categoryDropdown = new SelectList(cats, "CategoryID", "CategoryName");//in ja mgim ke farinkey CategoryID hast va to CategoryName ro neshon bedeh
																							 //کلاس SelectList به شما امکان می دهد لیست های کشویی یا لیست های چندگانه را انتخاب کنید.
			ViewBag.categoryDropdown = categoryDropdown;
		}
		private void InflateSupplierDrp()
		{
			var sups = ISupplierApp.GetAll();
			sups.Insert(0, new Supplier { SupplierID = -1, SupplierName = "...Please Select..." });
			SelectList supplierDropdown = new SelectList(sups, "SupplierID", "SupplierName");//in ja mgim ke farinkey CategoryID hast va to CategoryName ro neshon bedeh
																							 //کلاس SelectList به شما امکان می دهد لیست های کشویی یا لیست های چندگانه را انتخاب کنید.
			ViewBag.supplierDropdown = supplierDropdown;
		}
		#endregion
		private readonly ISupplierApplication ISupplierApp;
		private readonly ICategoryApplication ICategoryApp;
		private readonly IProductApplication IProductApp;
		private readonly IWebHostEnvironment env;
		public ProductManagementController(ISupplierApplication ISupplierApp, ICategoryApplication ICategoryApp, IProductApplication IProductApp , IWebHostEnvironment env)
		{
			this.ISupplierApp = ISupplierApp;
			this.ICategoryApp = ICategoryApp;
			this.IProductApp = IProductApp;
			this.env = env;
		}
		public IActionResult Index(ProductSearchModel sm)
		{
			InflateCategoryDrp();
			InflateSupplierDrp();
			return View(sm);
		}
		[HttpPost]
		public JsonResult Delete(int ProductID)//int ProductID in mishe sendingDate  JsonResult Delete in mishe sendingUrl
		{
			OperationResult op = IProductApp.Remove(ProductID);
			return Json(op);
		}
		public IActionResult Search(ProductSearchModel sm )
		{
			return ViewComponent("ProductList", sm);
		}
		public IActionResult AddNew()
		{
			InflateCategoryDrp();
			InflateSupplierDrp();
			return View();
		}
		[HttpPost]
		public IActionResult AddNew(ProductAddAndEditViewModel prod)//in AddNew Be hamrahe Amniant Saghte Shodeh (Amozesh Amniat)
		{
			if(!prod.Image.FileName.IsValidFileName())
			{
                TempData["ErrorMessage"] = "Invalid File Name";
                return RedirectToAction("Index", "ProductManagement");
            }
			if(!prod.Image.IsValidImageSize(1))
			{
				TempData["ErrorMessage"] = "File Size Must be between 40960 And 2097152";
				return RedirectToAction("Index" , "ProductManagement");
			}
			string fn = prod.Image.FileName.ToUniqueFileName();
			string dbFileName = $"~/ProductImages/{fn}";// in daghel data base zakhire mishe 
			var path = $"{env.ContentRootPath}/ProductImages/{fn}";// in adderss image in wwwroot hast ke be in migan Address Fiziki ke nesbat be reshe site sangideh mishavad ke be name relative gofteh mishavad
			FileStream fs = new FileStream(path, FileMode.Create);
			prod.ImagUrl = dbFileName;
			ProductAddEditModel model = new ProductAddEditModel
			{
				CategoryID = prod.CategoryID,
				Description = prod.Description,
				ImagUrl = dbFileName,
				JSONLDInformation= prod.JSONLDInformation,
				MataDescription= prod.MataDescription,
				MetaKeyWord= prod.MetaKeyWord,
				PageTitle= prod.PageTitle,
				ProductName = prod.ProductName,
				Slup = prod.Slup,
				SupplierID = prod.SupplierID,
				UnitPrice = prod.UnitPrice,
			};
			IProductApp.Register(model);
			prod.Image.CopyTo(fs);//in ja jaii ke file gharare copy beshe
			return RedirectToAction("Index" , "ProductManagement");
		}
	}
}

ESharpMashtiHasan/ViewComponents/ProductListViewComponent.cs
using ESharpMashtiHasan.Models;
using Microsoft.AspNetCore.Mvc;
using Shapping.DomainModel.BusinessModel.Product;
using Shopping.ApplicationServiceContract.Services;

namespace ESharpMashtiHasan.ViewComponents
{
	[ViewComponent(Name = "ProductList")]
	public class ProductListViewComponent : ViewComponent
	{
		private readonly IProductApplication IProductApp;
        public ProductListViewComponent(IProductApplication IProductApp)
        {
            this.IProductApp = IProductApp;
        }
		public IViewComponentResult Invoke(ProductSearchModel sm)
		{
			int rc = 0;
			var products = IProductApp.Search(sm, out rc);
			Models.ProductListAndSearchModel psm = new Models.ProductListAndSearchModel { sm = sm, productListItems = products };
			sm.RecordCount = rc;
			if (sm.PageSize == 0)
			{
				sm.PageSize = 5;
			}
			if (sm.RecordCount % sm.PageSize == 0)
			{
				sm.PageCount = sm.RecordCount / sm.PageSize;
			}
			else
			{
				sm.PageCount = sm.RecordCount / sm.PageSize + 1;
			}
			return View(psm);
		}
	}
}

ESharpMashtiHasan/Views/ProductManagement/AddNew.cshtml
@model ESharpMashtiHasan.ViewModel.Products.ProductAddAndEditViewModel
@{
	Layout = null; 
	SelectList categoryDropdown = (SelectList)ViewBag.categoryDropdown;
	SelectList supplierDropdown = (SelectList)ViewBag.supplierDropdown;
}
<form asp-action="AddNew" asp-controller="ProductManagement" method="post" enctype="multipart/form-data">@* enctype="multipart/form-data" in ro agar nazarim Image null rad mishehe *@
	
	<table class="table table-hover table-sm table-bordered table-striped">
		<tr>
			<td>
				<label for="CategoryID">Category</label>
			</td>
			<td>
				<select asp-items="categoryDropdown " class="form-control" asp-for="CategoryID"></select>
			</td>
		</tr>
		<tr>
			<td>
				<label for="SupplierID">Supplier</label>
			</td>
			<td>
				<select asp-for="SupplierID" class="form-control" asp-items="supplierDropdown"> </select>
			</td>
		</tr>
		<tr>
			<td>
				ProductName
			</td>
			<td>
				<input type="text" asp-for="ProductName" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				UnitPrice
			</td>
			<td>
				<input type="text" asp-for="UnitPrice" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				PageTitle
			</td>
			<td>
				<input type="text" asp-for="PageTitle" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				Slug
			</td>
			<td>
				<input type="text" asp-for="Slup" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				MataDescription
			</td>
			<td>
				<input type="text" asp-for="MataDescription" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				MetaKeyWord
			</td>
			<td>
				<input type="text" asp-for="MetaKeyWord" class="form-control" />
			</td>
		</tr>
		<tr>
			<td>
				JSONLDInformation
			</td>
			<td>
				<input type="text" asp-for="JSONLDInformation" class="form-control" />
			</td>
		</tr>
		<tr>
			<td colspan="2" class="text-center">
				Description
			</td>
			<td colspan="2" class="text-center">
				<textarea class="form-control" cols="60" rows="10" asp-for="Description"></textarea>
			</td>
		</tr>
		<tr>
			<td>
				Image
			</td>
			<td>
				<input type="file" asp-for="Image" />
			</td>
		</tr>
		<tr>
			<td colspan="2" class="text-center">
				@* in addNew not ajax hast *@
				<input class="btn btn-success" name="name" value="Add New" />
				<span class="btn btn-success" id="btnCancel">Cancel</span>
			</td>
		</tr>
	</table>
</form>

ESharpMashtiHasan/Views/ProductManagement/Index.cshtml
    @model Shapping.DomainModel.BusinessModel.Product.ProductSearchModel
@{
    SelectList categoryDropdown = (SelectList)ViewBag.categoryDropdown;
    SelectList supplierDropdown = (SelectList)ViewBag.supplierDropdown;
}
<form method ="get" asp-action="Index" asp-controller="ProductManagement" id="frmSearch">
    <table class=" table table-hover table-bordered table-sm table-striped">
        <tr>
            <td>
                <label for="CategoryID">Category</label>
            </td>
            <td>
               <select asp-items="categoryDropdown " class="form-control" asp-for="CategoryID"></select>
            </td>
        </tr>
        <tr>
            <td>
                <label for="SupplierID">Supplier</label>
            </td>
            <td>
                <select asp-for="SupplierID" class="form-control" asp-items="supplierDropdown"> </select>
            </td>
        </tr>
        <tr>
            <td>
                <label for="UintPriceFrom">UnitPriceFrom</label>
            </td>
            <td>
                <input type="text" class="form-control" placeholder="UintPriceFrom" asp-for="UintPriceFrom" />
            </td>
        </tr>
        <tr>
            <td>
                <label for="UintPriceTo">UnitPriceTo</label>
            </td>
            <td>
                <input type="text" class="form-control" placeholder="UintPriceTo" asp-for="UintPriceTo" />
            </td>
        </tr>
        <tr>
            <td>
                <label for="ProductName">ProductName</label>
            </td>
            <td>
                <input type="text" class="form-control" placeholder="ProductName" asp-for="ProductName" />
            </td>
        </tr>
        <tr>
            <td>
                <label for="Slug">Slug</label>
            </td>
            <td>
                <input type="text" class="form-control" placeholder="Slug" asp-for="Slug" />
            </td>
        </tr>
        <tr>
            <td class="text-center " colspan="2">
                <input type="submit" value="Search" class="btn btn-success " />
                <a asp-action="Index" asp-controller="ProductManagement" class="btn btn-primary">Remove Filter</a>
                <span class="btn btn-primary" id="btnAddNewProduct">Add</span>
            </td>
        </tr>
    </table> 
    <div id="dvContent">
		@await Component.InvokeAsync("ProductList", this.Model)  @**@
	</div>
</form>